### ISSUE TITLE
plUploadBaseHandler ln 124

### ISSUE THREAD

**Issue by jesusgarza** [RickStrahl/Westwind.plUploadHandler#4]
Is this right?
if (chunk => chunks - 1)

I get an lambda expression error. Shouldn't be

if (chunk >= chunks - 1) ?

**Comment by jonbakerfish** [comment]
@jesusgarza  I think you are right.

**Comment by RickStrahl** [comment]
Huh? That's not a lambda and C# doesn't care about the precedence of the signs. Either way is valid and should compile fine.

Where is is this failing? Compile time? In what version of .NET?

**Comment by jonbakerfish** [comment]
@RickStrahl I use vs2010 and .NET 4.0

**Comment by RickStrahl** [comment]
And you get what? Compiler error?

**Comment by jonbakerfish** [comment]
@RickStrahl 
plUploadBaseHandler.cs (124,21): error CS1660: Can not convert lambda expression type "bool", because it is not a delegate type
plUploadBaseHandler.cs (124,21): error CS0136: can not declare a local variable called "chunk" in this context, because it would be "chunk" has a different meaning, and it has been in the "parent or current 'scope said the other content

**Comment by RickStrahl** [comment]
Ok... odd could have sworn that this worked just fine, but sure enough it failed for me as well. Fixed and updated in the repository. Thanks...
